controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["wheel_left_joint"]
    right_wheel_names: ["wheel_right_joint"]

    wheel_separation: 0.5
    wheel_radius: 0.1

    base_frame_id: base_link
    odom_frame_id: odom

    publish_rate: 50
    use_stamped_vel: false

    enable_odom_tf: true
