ekf_filter_node:
  ros__parameters:

    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true

    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom

    # ================= ODOMETRY =================
    odom0: /odom
    odom0_config: [true,  true,  false,
                   false, false, true,
                   true,  true,  false,
                   false, false, false,
                   false, false, false]
    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: false

    # ================= IMU =================
    imu0: /imu/data
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  true,  true,  true,
                  false, false, false]
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

    # ================= GPS =================
    gps0: /gps/fix
    gps0_queue_size: 5
    gps0_config: [true,  true,  false,
                  false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, false]

    # ================= PROCESS NOISE =================
    process_noise_covariance: [
      0.05, 0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.05, 0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.05, 0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.05, 0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.05, 0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.05
    ]
